name: TidyBayti Docker Image

on:
  push:
    branches: ["stage"]
  pull_request:
    branches: ["stage"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build . --file Dockerfile --tag "${{ secrets.DOCKERHUB_USERNAME }}/tidy-ci-cd:latest"

      - name: Push Docker image
        run: docker push "${{ secrets.DOCKERHUB_USERNAME }}/tidy-ci-cd:latest"
